- client/src/App.tsx
- client/src/commons/atoms/buttons/Button.styled.tsx
- client/src/commons/atoms/buttons/PurpleBtn.tsx
- client/src/commons/atoms/buttons/category/CategoryButton.tsx
- client/src/commons/atoms/buttons/login/LoginBtn.styled.tsx
- client/src/commons/atoms/buttons/login/LoginBtn.tsx
- client/src/commons/atoms/footer/Footer.styled.tsx
- client/src/commons/atoms/header/Header.styled.tsx
- client/src/commons/atoms/header/Header.tsx
- client/src/commons/atoms/logo/Logo.styled.tsx
- client/src/commons/atoms/navbar/CategoryNavBar.tsx
- client/src/commons/atoms/user/UserImg.styled.tsx
- client/src/components/bookmark/Bookmark.styled.tsx
- client/src/components/dropdown/Dropdown.styled.tsx
- client/src/components/dropdown/Dropdown.tsx
- client/src/components/search/Search.styled.tsx
- client/src/components/webItem/WebItem.styled.tsx
- client/src/pages/main/Main.styled.tsx
- client/src/pages/main/Main.tsx
- client/src/stories/buttons/Buttons.stories.tsx
- client/tsconfig.json
메인 페이지 추합 작업입니다. 
1. 글자가 들어가는 부분은 whitespace-nowrap 속성을 추가하여 창 사이즈가 줄어들더라도 다음 줄로 넘어가지 않도록 수정하였습니다. 
2. 북마크 부분은 props 설정 시 타입 미 설정으로 우선 주석 처리 하였습니다. src/Bookmarked.styled.tsx
3. 카테고리 아이템 메인 페이지 정렬은 Array.from(length: 4) 형식으로 4개 우선 불러오는 작업 진행했습니다. 
4. 카테고리 Nav 에 focus 요소 추가하였습니다. 
5. Button 은 Button.styled.tsx 사용하여 children 부분 안에 글자 작성해서 사용 할 수 있게 변경 하였습니다.
> Design: 메인 페이지 추합 작업

- client/src/commons/atoms/buttons/Button.styled.tsx
- client/src/commons/atoms/buttons/PurpleBtn.tsx
- client/src/commons/atoms/buttons/writing/writingBtn.tsx
게시판 목록의 Writing Button 관련 PR 입니다. 
1. 버튼의 활용을 위해 한번 더 폴더 구조를 수정하였습니다. 
```bash
└─buttons
└─caategory
└─login
└─writing
└─Button.styled.tsx
└─PurpleBtn.tsx
```
* 각 category/login/writing 폴더 안에는 커스터마이징 버튼이 있습니다. 
- 추합할 때 해당 컴포넌트 이름만 불러오면 됩니다. 
- 예시 : ```<WritingBtn/>```
* Button.styled.tsx 파일 안에는 다양한 커스터마이징이 적용된 버튼들이 있습니다. 
* PurpleBtn.tsx 파일은 각 기본 보라색 버튼의 최종 모체입니다. 
#스크린샷
> Design: 게시판 목록의 writing Button 생성

- client/src/commons/atoms/buttons/Button.styled.tsx
- client/src/commons/atoms/buttons/PurpleBtn.tsx
- client/src/commons/atoms/buttons/writing/DeleteBtn.tsx
- client/src/commons/atoms/buttons/writing/EditBtn.tsx
- client/src/commons/atoms/buttons/writing/SaveBtn.tsx
- client/src/commons/atoms/buttons/writing/writingBtn.tsx
게시물 상세 페이지에서 하단의 삭제/수정 버튼 생성
1. 게시물 삭제 / 수정 버튼
- bg-zinc-300 # d4d4d8 색깔로 작업했습니다. 
- Hover 시에만 HOVER_COLOR 적용 됩니다. 
2. 댓글 저장 버튼 
- 위 삭제/수정 버튼과 동일하게 동작합니다. 
<br/>
> Design: 게시물 상세 페이지의 삭제/수정 버튼  + 및 댓글 저장 버튼 생성

- client/src/commons/atoms/footer/Footer.styled.tsx
- client/src/components/mypage-community/CommunityList.styled.tsx
- client/src/components/mypageItem/MypageItem.styled.tsx
- client/src/components/mypageProfile/MypageProfile.styled.tsx
- client/src/components/mypageProfile/MypageProfile.tsx
- client/src/index.css
- client/src/pages/mypage/MyPage.styled.tsx
- client/src/pages/mypage/Mypage.tsx
마이 페이지 추합 작업 PR 입니다. 
1. 내가 쓴 글의 목록 부분의 아이템
* Hover 효과 사이즈 증가 -> 색상 변경 
* width  길이 고정  
2. 전체적인 구조 justify-center 고정 
3. 내 게시물과 좋아요 게시물 의 경우는 가로 스크롤 
4. 게시판 목록은 추후 페이지네이션 적용 예정
게시판 목록의  페이지네이션 구현이 필요합니다.
> Design: mypage 추합 작업

- client/src/commons/atoms/Card.tsx
- client/src/commons/atoms/Image.tsx
- client/src/commons/atoms/Label.tsx
- client/src/commons/atoms/Typography.tsx
- client/src/commons/atoms/buttons/category/CategoryButton.tsx
- client/src/commons/atoms/dropdown/DropDownBox.tsx
- client/src/commons/atoms/dropdown/DropDownItem.tsx
- client/src/commons/atoms/header/CHeader.styled.tsx
- client/src/commons/molecules/CategoryDropDown.tsx
- client/src/commons/molecules/Comment.tsx
- client/src/commons/molecules/CommentWriteBox.tsx
- client/src/commons/molecules/IconInput.tsx
- client/src/commons/molecules/Tag.tsx
- client/src/commons/molecules/UserProfile.tsx
- client/src/commons/styles/Buttons.styled.tsx
- client/src/commons/styles/Containers.styled.tsx
- client/src/commons/styles/Inputs.styled.tsx
- client/src/commons/styles/StyleList.ts
- client/src/components/CommentBox.tsx
- client/src/components/edit/TitleForm.tsx
- client/src/components/navbar/CategoryNavBar.tsx
- client/src/stories/atoms/buttons/Buttons.stories.tsx
- client/src/stories/components/DropDown.stories.tsx
- client/src/stories/components/Form.stories.tsx
- client/src/stories/components/Tags.stories.tsx
- client/src/stories/components/UserProfile.stories.tsx
- client/src/types/StyleType.ts
* 게시물 상세보기 페이지에 존재하는 댓글 컴포넌트를 작업했습니다.
* `commons/atoms/Card` - 하얀색 둥근 border-radius를 가진 카드 컴포넌트입니다.
* `commons/molecules/Comment` - 댓글 아이템 한 개의 컴포넌트입니다.
* `commons/molecules/CommentWriteBox` - 댓글 작성란 컴포넌트입니다.
* `components/CommentBox` - 게시물 상세보기 페이지 우측에 존재하는 댓글 컴포넌트입니다.
* 제가 폭을 full로 한 이유는 페이지를 추합하실 때 글 부분과 댓글 부분이 어떤 비율로 나눠질지 몰라 페이지 정렬하는 컨테이너 비율에 맞게 크기가 조정되도록 만든 것입니다.(세로 길이도 더 길게 고정시키면 justify-between으로 해놔서 댓글이 적을 경우에 댓글 작성란과 거리가 띄워질 겁니다.)
* 각 컴포넌트마다 존재하는 interface 정의는 기능 구현 시 객체로 정리하시면 됩니다. 그냥 당장 브라우저에 그리기 위해 필요한 데이터 하나하나를 나열했습니다. `comment: 'CommentProps'` 와 같이 문자열로 표현한 건 나중에 저런 식으로 객체를 분리해 타입으로 받으면 된다는 걸 명시하는 목적으로 적은 겁니다.
* 피그마에 댓글 페이지네이션 빠져있는 거 뒤늦게 깨달았는데 당장 제가 pull 한 컴포넌트에는 아직 페이지네이션 컴포넌트가 없어서, 일단 빼둔채로 push합니다. 나중에 기능 구현하시는 분이 넣어도 충분할 것 같습니다.
> [FRONT] 게시물 상세보기 페이지 댓글 컴포넌트 UI

- client/src/commons/atoms/Label.tsx
- client/src/commons/molecules/UserProfile.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.styled.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* 포트폴리오 상세보기 페이지에 태그 컴포넌트 추가했습니다.
* 사용자 소개 부분 padding, gap 조금 추가하였습니다.
* 의뢰요청 버튼은 크기 큰 버전으로 어떻게 재사용하는지(PurpleBigBtn..?) 잘 모르겠어서 못 고쳤습니다ㅜ.ㅜ
> [FRONT] 포트폴리오 상세보기 페이지 태그 추가 & 정렬 간격 수정

- client/src/App.tsx
- client/src/commons/atoms/Label.tsx
- client/src/commons/atoms/Typography.tsx
- client/src/commons/atoms/buttons/revise-remove/RemoveBtn.tsx
- client/src/commons/atoms/buttons/revise-remove/ReviseBtn.tsx
- client/src/commons/atoms/header/CHeader.styled.tsx
- client/src/commons/atoms/header/CHeader.tsx
- client/src/commons/molecules/Comment.tsx
- client/src/commons/molecules/UserProfile.tsx
- client/src/commons/styles/Inputs.styled.tsx
- client/src/components/detailContents/DetailContents.styled.tsx
- client/src/pages/community-add/AddCommunity.tsx
- client/src/pages/community-detail/CommunityDetail.styled.tsx
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/community-main/CommunityMain.tsx
- client/src/pages/mypage/MyPage.styled.tsx
- client/src/types/index.ts
UI 추합 작업 4차 입니다. 
- 전반적인 UI 수정 
- 배경 이미지 헤더에 적용 ( 헤더 fix 아직 미 작업)
- 링크 연결 
* CHeader 의 Recruitment와 Community 는 링크 작업 하지 않았습니다. 
해당 컴포넌트가 게시판 메인에서는  검정색 글씨, 게시판 상세 페이지에서는 하얗색 글씨가 적용되어야 했기에 type에 'blackboard' 를 추가하였고, if문으로 조건에 맞추어 알맞는 컴포넌트 구조를 반환합니다. 
```javascript
interface UserProfileProps {
type: 'board' | 'comment' | 'portfolio' | 'blackboard';
username: string;
date?: string;
}
const ImageSizes: any = {
board: 65,
comment: 35,
portfolio: 100,
blackboard: 65
}
const UserProfile = ({ type, username, date }: UserProfileProps) => {
return (
<FlexWrapper gap={15} className='items-center'>
<Image url={userImg} shape='circle' size={ImageSizes[type]} />
{(() => {
if (type === 'board') {
return (
<FlexColumnWrapper gap={0}>
<Label text={username} type={type} />
<span>{date}2022.06.30</span> …
```
> Design: UI 추합 작업 4차 

- client/src/commons/molecules/Comment.tsx
- client/src/commons/molecules/CommentWriteBox.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* UserProfile 컴포넌트 props가 변했기 때문에 UserProfile이 포함된 페이지마다 수정을 해주었습니다.
* 임시 user객체를 보냈습니다. 그래서 이미지도 안 뜰 거예요. 나중에 msw로 가짜 데이터 넣으실 때 picture 칼럼에 이미지 url 넣으신 뒤 GET 요청하면 잘 받아집니다.
* 제가 빠트린 부분이 있다면 UserProfile 컴포넌트가 포함된 해당 페이지가 아예 안 나올 수 있습니다. 유저프로필 props 때문이니 user 객체를 인자로 전달해주세요.
> Fix: UserProfile이 들어가는 페이지에 임시 user props를 전달한다.

- client/src/App.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/views/Views.tsx
- client/src/pages/community-main/CommunityMain.tsx
게시판 메인 페이지 목록 조회 기능 구현 PR 입니다. 
- Communit-main page 에서 전체 게시판 목록 조회를 위해 GET 요청 코드 작성 
- msw 사용해서 더미 데이터로 코드 테스트 완료
**특이사항**
- 현재는 기업 공고와 파트너 게시판 구분하지 않음.
> Feat: 게시판 메인 페이지 목록 조회 기능 구현

- client/src/App.tsx
- client/src/commons/atoms/Card.tsx
- client/src/commons/atoms/buttons/writing/SaveBtn.tsx
- client/src/commons/molecules/Comment.tsx
- client/src/commons/molecules/CommentWriteBox.tsx
- client/src/components/CommentBox.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/detailContents/DetailContents.tsx
- client/src/mocks/data.ts
- client/src/mocks/handlers.ts
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/community-main/CommunityMain.tsx
- client/src/types/index.ts
게시판 상세 페이지 조회 기능 구현 
- 게시판 메인에서 원하는 게시판 클릭 시 해당하는 게시판 상세 페이지로 이동 되며 관련된 댓글들도 조회 됩니다. 
- 댓글 등록 기능 구현 완료 
- Card 컴포넌트에서 댓글 등록 폼을 하단으로 위치 고정
- 댓글 폼을 왼쪽 Content 와 동일하게 h-700px로 고정
- 댓글 handler 에서 board_id를 불러올 수가 없어서 임의로 2로 지정해둔 상태입니다. 
* 테스트 결과 전부 댓글 등록 기능 구현 되지만 handler에서는 2에서만 데이터가 추가 되는 것을 확인 할 수 있습니다. 
- 유저프로필은 추후 백엔드에서 api 로 사진 불러올 때 그때 추가 수정 예정입니다. 
- 댓글 등록 오늘 날짜도 수정 작업 예정입니다.
> Feat: 게시판 상세 페이지 조회 기능 구현

- client/src/App.tsx
- client/src/commons/molecules/Comment.tsx
- client/src/components/CommentBox.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/mocks/data.ts
- client/src/mocks/handlers.ts
- client/src/mocks/infiniteScrollData.ts
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/types/index.ts
- client/src/utils/ApiService.tsx
게시판 API 명세서 수정에 따른 변수 이름 변경 및 주석 정리 관련 PR 입니다. 
- CommunityDetail/ CommentBox, data, handler, App. 에서 사용되던 board_id 와 member_id를 각각 id와 memberId로 수정하였습니다. 
- 불필요한 주석 정리 
- 현재 무한 스크롤 테스트를 위해 _**게시판 전체 더미 데이터 : commu**_ 를 별도로 infiniteScrolldata로 빼서 게시판 목록 데이터들을 관리중입니다. 
게시판 목록 중 테스트4 이름의 게시물들은 눌러도 상세 페이지로 이동 하지 않습니다.
> Rename: 게시판 부분 APi 명세서에 따른 변수 이름 변경 및 주석 정리 

- client/src/commons/molecules/CategoryDropDown.tsx
* isOpen <-> isOpened 변수명이 일치하지 않아 발생한 에러를 수정하였습니다.
> Fix: CategoryDropDown 컴포넌트에 isOpened 변수명 에러를 해결한다.

- client/src/assets/data/categoryTags.ts
- client/src/commons/atoms/dropdown/DropDownItem.tsx
- client/src/commons/molecules/Tag.tsx
- client/src/components/editor/TitleForm.tsx
- client/src/hooks/useTagSelect.tsx
- client/src/modules/tagSlice.ts
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* `assets/data/categoryTags` 에 고유한 key 값이 될 id를 중복되게 만들어(1,2,3,4 반복) 발생한 태그 체크 오류를 수정하였습니다.
* 특정 카테고리에서 태그를 고른 후 태그 취소를 하지 않고 다른 카테고리로 변경했을 때, 지금까지 선택한 모든 태그를 초기화 시켰습니다.
* 포트폴리오 상세보기 페이지에서 태그 클릭 css 옵션을 막았습니다.
> Fix: 고유 key 중복으로 인한 태그 체크 오류를 수정한다.

- client/src/commons/atoms/header/CHeader.tsx
- client/src/commons/atoms/header/Header.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/mocks/handlers.ts
- client/src/pages/community-main/CommunityMain.tsx
커뮤니티 메인 페이지에서 헤더의 게시판 구분에 따른 목록 조회 기능 구현
- 헤더의 게시판 클릭에 따른 목록 조회 기능 구현 
* handler 부분 쿼리스트링에 따른 반환 값 수정
> Feat: CommunityMain에서 게시판 별 구분 기능 구현

- client/src/components/appItem/AppItem.tsx
- client/src/components/graphicItem/GraphicItem.tsx
- client/src/components/photoItem/PhotoItem.tsx
- client/src/components/threeDitem/ThreeDITem.tsx
- client/src/components/webItem/WebItem.tsx
- client/src/mocks/handlers.ts
- client/src/mocks/infiniteScrollData.ts
- client/src/pages/main/Main.tsx
- client/src/utils/apiService.tsx
메인 카테고리 페이지 관련 더미 데이터 제작 및 get 조회 기능 구현
- 메인 카테고리 별 더미 데이터 제작 
- GET 이용하여 카테고리 별 데이터 조회 : hover 시 포트폴리오 title과 name 
* 북마크 전부 false : 전역 관리 미 구현 
* 포트폴리오 이미지 백엔드에 요청 필요 ( 현재 더미데이터에 없음)
- tailwind-styled-components 삭제 되어서 추가 설치 : package-json 추가 했으나.. 이 PR 에는 안 올라간다.
> Feat: 카테고리 메인 페이지 dummydata 구현

- client/src/App.tsx
- client/src/pages/community-add/AddCommunity.tsx
게시판 상세 페이지 조회 및 수정 후 저장 기능 수정 
- App.tsx 에서 addCommunity 페이지 경로 미스 설정
- AddComunity 파일에서 pathname을 통해서 url의 정보를 불러오지 못해서 생긴 오류 수정
> Fix: 게시판 상세 페이지 조회 및 수정 후 저장 기능 수정

- client/src/components/comment/CommentBox.tsx
- client/src/pages/community-detail/CommunityDetail.tsx
댓글 commentBox 에서 상위 컴포넌트로부터 useState 받는 부분에 에러 #321 발생하여 삭제. 
useState 부분 삭제 시 댓글 등록 시 새로 고침을 해야 새롭게 글이 등록 되는 부분 해결 필요. 
- 현재 refresh token 문제로 일단 보류
> Fix: 댓글 react #321 error 해결 위해 useState 삭제

- client/src/commons/atoms/buttons/category/CategoryButton.tsx
- client/src/components/header/CHeader.styled.tsx
- client/src/components/header/Header.styled.tsx
- client/src/components/navbar/CategoryNavBar.tsx
- client/src/components/ranking/Ranking.styled.tsx
- client/src/components/ranking/Ranking.tsx
- client/src/pages/main/Main.styled.tsx
- client/src/pages/main/Main.tsx
메인 카테고리 랭킹 기능 추가 ( 조회수 기준 ) + 헤더 (fixed) + 카테고리 focus 효과 추가 관련 PR 입니다.
1. 메인 카테고리에서 카테고리 별로 조회수 기준 오늘의 랭킹 기능을 추가하였습니다. 
2. 헤더와 카테고리의 위치를 top-0 으로 fixed 하여 스크롤을 내려도 기능을 사용할 수 있습니다. 
3. 카테고리 focus border 효과 추가하여 직관적으로 UI 수정하였습니다. 
1. 몇 사진이 깨지는 현상이 발생했습니다. 
2. mouse move event 도 적용할 예정입니다. 더불어 현재는 그저 overflow-scroll 이지만 클릭으로 넘어갈 수 있게도 할 예정입니다. 
3. 현재는 한번 페이지 랜딩시 마다 조회되는 데이터의 조회수 기준이지만 특정 시간 기준 자동 업데이트 되도록 수정할 예정입니다. 
4. 헤더와 카테고리의 배경이 투명하여 스크롤 다운 시 메인 아이템들과 겹쳐 육안으로 잘 확인 되지 않는 현상이 있습니다.
> Feat: 메인 카테고리 랭킹 기능 추가 + 헤더(fixed) + 카테고리 focus 효과 추가

- client/src/pages/main/Main.tsx
메인 페이지의 랭킹 업데이트를 6시간 마다 업데이트 되도록 설정한 PR 입니다. 
- setInterval 메서드를 사용하여 6시간 마다 랭킹 자료가 업데이트 되도록 설정하였습니다. 
- useEffect 함수에 6시간 업데이트 시 변경되는 시간의 값에 따라 페이지가 리랜더링되어 메인 랭킹 자료도 새롭게 업데이트 될 수 있도록 하였습니다.
> Feat: 메인페이지 랭킹 6시간 마다 업데이트 설정

- client/src/hooks/useToggle.tsx
* useToggle 훅의 onClick 함수에 useCallback이 불필요하다고 판단하여 제거했습니다.
> Fix: useToggle에서 useCallback을 제거한다.

- client/src/components/ranking/Ranking.tsx
- client/src/pages/main/Main.tsx
메인 페이지 랭킹 기능 최초값 설정 및 설정한 6시간 업데이트 될 때 랭킹 시간 업데이트 안되었던 에러 수정한 PR 입니다. 
Main컴포넌트로 `handleTime()`을 빼고 Ranking 컴포넌트에서 별도로 useEffect를 적용하였습니다. 
:  Main의 ScrollTo(0,0)요소와 겹치는 이중 상태 변경에 따른 경고 원인을 제거하였습니다. 
Main의 timeUpdate 요소의 최초값을 handleTime() 내부 함수로 적용하여 기존의 "..." 로 표시되던 최초값이 시간으로 표시될 수 있게 하였습니다.
> Fix: 랭킹 기능 최초값 설정 및 시간 업데이트에 따른 시간 업데이트 미 적용 부분 수정 
