codestates-seb/seb44_main_013

- client/src/commons/styles/Globalcolor.tsx
미리 선정한 포인트 색상과 기본 색상을 전역으로 사용할 있게 작성한 파일입니다.
> [FRONT] Design : global style 선정

- client/src/components/Temp.tsx
- client/tailwind.config.js
tailwindcss  에서 전역 색상 관리 파일과 컴포넌트 폴더 생성했습니다.
> [FRONT] Design : tailwindcss global color + components file

- client/package-lock.json
- client/package.json
- client/src/index.css
- client/src/main.tsx
개요 
tailwindcss 사용을 위한 패키지 제이슨 추가 및 index.css + main.tsx 수정
> [FRONT]Choree : tailwindcss 사용을 위한 pacakge.json 추가

- client/src/commons/Footer.tsx
Footer UI 컴포넌트 관련 PR 입니다. 
- tailwindcss를 사용하여 간단한 Footer UI 생성
> [FRONT] Design: Footer UI 컴포넌생성

- client/src/components/views/Views.styled.tsx
- client/src/components/views/Views.tsx
조회수 구현
- 조회수 구현
- position 설정
- 폰트 사이즈 설정
> Design: community views(조회수) 구현

- client/src/components/communityItem/CommunityItem.styled.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/views/Views.styled.tsx
- client/src/components/views/Views.tsx
community의 community item 구현
- item 레이아웃 구현
- item title(h2)
- item contents(p)
- 조회수 배치(views)
- 그림자 효과
- padding 값 지정
> Design: community item 구현

- client/src/commons/atoms/buttons/revise-remove/RemoveBtn.tsx
- client/src/commons/atoms/buttons/revise-remove/ReviseBtn.tsx
> [Add] 수정 삭제 버튼 생성

- client/src/pages/community-list/CommunityList.styled.tsx
- client/src/pages/community-list/CommunityList.tsx
- client/src/pages/community/Community.styled.tsx
- client/src/pages/community/Community.tsx
게시판에 글을 등록하는 페이지 마크업 작업 구현햇습니다.
> [add] 게시판 등록/수정 페이지 생성

- client/src/components/mypage-community/CommunityList.styled.tsx
- client/src/components/mypage-community/CommunityList.tsx
마이페이지에서 보여질 커뮤니티 게시판 리스트를 UI작업 했습니다.
> [add] 게시판 리스트 컴포넌트

- client/src/commons/styles/Containers.styled.tsx
- client/src/components/pagenation/Pagenation.styled.tsx
- client/src/components/pagenation/Pagenation.tsx
- client/src/pages/mypage/Mypage.tsx
마이페이지의 내 게시글 관리 section의 페이지네이션 UI 구현 PR 입니다. 
- components 폴더에 Pagenation 컴포넌트 생성 후 mypage 에 적용 하였습니다. 
* 기능 x.  hover / focus 효과 o
> Design: mypage의 페이지네이션 UI 구현

- client/src/pages/community-add/AddCommunity.styled.tsx
- client/src/pages/community-add/AddCommunity.tsx
에디터를 커스텀하여 이미지, 링크, 동영상 기능을 더하고 저장위치를 에디터 안으로 배치 했습니다.
> [styled] 에디터작업 수정, 버튼 위치 수정

- client/src/App.tsx
- client/src/commons/atoms/buttons/Button.styled.tsx
- client/src/commons/atoms/logo/Logo.styled.tsx
- client/src/commons/styles/MainLayout.tsx
- client/src/components/editor/TitleForm.tsx
- client/src/components/header/LogoHeader.tsx
- client/src/components/headerDropdown/HeaderDropdown.tsx
- client/src/pages/main/Main.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.styled.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
- client/src/pages/portfolio-edit/PortfolioEdit.tsx
UI 추합 작업 2차 임시 PR 입니다. 
각자 pull  받으셔서 기능 구현 부탁드려요 감사합니다.
> Design: 2차 UI 작업 

- client/src/commons/atoms/header/Header.styled.tsx
- client/src/commons/atoms/header/Header.tsx
- client/src/components/search/Search.styled.tsx
Header UI  구조 수정 완료 및 ** 이미지 찌그러지는 이슈 토스 ** 
1. Header Search 바 왼쪽으로 치우쳐져있는 정렬 개선 
2. 게시판 글씨 가운데 정렬 개선 
3. 헤더 px-3 으로 축소 개선
> Design: Header UI 수정 완 및 토스

- client/src/components/headerDropdown/HeaderDropdown.styled.tsx
- client/src/components/headerDropdown/HeaderDropdown.tsx
헤더 모달에 호버 효과가 적용이 되지 않은 이유를 찾고 문제를 해결했습니다.
> [styled] 헤더 모달 호버 효과 수정

- client/src/commons/molecules/CommentWriteBox.tsx
- client/src/commons/molecules/UserProfile.tsx
- client/src/commons/styles/Containers.styled.tsx
- client/src/commons/styles/Inputs.styled.tsx
- client/src/pages/community-detail/CommunityDetail.styled.tsx
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/community-main/CommunityMain.styled.tsx
- client/src/pages/community-main/CommunityMain.tsx
> Design: UI 추합 수정 작업 3차

- client/src/pages/community-main/CommunityMain.styled.tsx
- client/src/pages/community-main/CommunityMain.tsx
> [styled] 게시판 메인 페이지

- client/src/components/headerDropdown/HeaderDropdown.styled.tsx
헤더 모달의 배경에 투명도 0.9정도로 수정하고 w-40으로 살짝 줄여서 수정했습니다.
> [styled] 헤더 모달 스타일 수정

- client/src/components/detailGuide/DetailGuide.styled.tsx
- client/src/pages/community-add/AddCommunity.styled.tsx
- client/src/pages/community-add/AddCommunity.tsx
게시판 등록/수정 페이지 레이아웃 수정
- 전체 레이아웃 배치 수정
- quill, guide css 수정
> Design: 게시판 등록/수정 페이지 레이아웃 수정

- client/src/commons/atoms/buttons/LikeBtn.tsx
- client/src/commons/styles/Containers.styled.tsx
- client/src/hooks/useLikeBtn.tsx
- client/src/mocks/data.ts
- client/src/mocks/handlers.ts
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
- client/src/utils/ApiService.tsx
* 좋아요 버튼 기능을 구현하였습니다.
* CustomHook을 사용하였고, hooks/useLikeBtn.tsx 파일이 해당 훅 파일입니다.
* 현재 MSW로 테스트 했을 때 정상 작동 확인했습니다.
> Feat: 좋아요 버튼 기능을 구현한다.

- client/src/commons/atoms/buttons/LikeBtn.tsx
- client/src/hooks/useLikeBtn.tsx
- client/src/mocks/data.ts
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* LikeBtn.tsx, useLikeBtn.tsx 두 파일에 중복 인터페이스 선언이 있어 하나로 통일했습니다.
* MSW data에 isLiked 값을 true로 변경했습니다.
> Fix: LikeBtn & useLikeBtn 두 개의 PropsType을 동일화한다.

- client/src/mocks/handlers.ts
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* 포트폴리오 상세보기 페이지에 조회수 UI 및 카운트 기능을 추가하였습니다.
* MSW로 GET 요청 시 조회수가 한 번 카운트 됩니다.
> Feat: Portfolio Detail Page에 조회수를 추가한다.

- client/src/components/editor/QuillEditor.tsx
- client/src/components/editor/TitleForm.tsx
- client/src/pages/portfolio-edit/PortfolioEdit.tsx
- client/src/types/QuillPropsType.ts
- client/src/types/index.ts
* React Quill 에디터에 작성한 내용을 TitleForm 컴포넌트에 props로 전달합니다.
* 추후 TitleForm 컴포넌트에서 전달받은 값 + 제목, 카테고리, 태그, 설명문을 모두 합쳐 POST 요청을 보낼 예정입니다.
> Feat: Editor에서 텍스트를 입력받아 TitleForm에 전달한다.

- client/src/commons/styles/Buttons.styled.tsx
- client/src/components/editor/QuillEditor.tsx
- client/src/components/editor/TitleForm.tsx
- client/src/pages/portfolio-edit/PortfolioEdit.tsx
* react-hook-form 을 사용하여 react-quill에서 입력받은 내용과 TitleForm에서 입력받은 제목을 Form으로 합쳐 Submit 합니다.
> Feat: Title을 포함한 데이터를 Form으로 제출한다.

- client/src/components/search/Search.tsx
- client/src/pages/community-add/AddCommunity.tsx
- client/src/pages/community-main/CommunityMain.tsx
게시판 메인페이지 검색창 기능 구현
- 제목, 내용, 작성자로 검색
- 엔터키를 입력해야 검색 내용 렌더링
> Feat: 게시판 메인페이지 검색창 기능 구현

- client/src/App.tsx
- client/src/commons/atoms/Card.tsx
- client/src/commons/atoms/buttons/writing/SaveBtn.tsx
- client/src/commons/molecules/Comment.tsx
- client/src/commons/molecules/CommentWriteBox.tsx
- client/src/components/CommentBox.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/detailContents/DetailContents.tsx
- client/src/mocks/data.ts
- client/src/mocks/handlers.ts
- client/src/pages/community-detail/CommunityDetail.styled.tsx
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/community-main/CommunityMain.tsx
- client/src/types/index.ts
댓글 등록 기능 구현 중 파일 누락 된 CommentBox부분 관련 추가 PR 입니다. 
부득이하게 깃 push 가 원래 branch로 하는 것이 거절 되어서 새로 생성 후 PR 합니다. 
230712 추가
댓글 수정 기능 구현 
- 수정 버튼 클릭 시 click to edit 과 비슷하게 댓글 부분이 input으로 변경되고 수정 할 수 있습니다. 
* 빈 댓글을 남겼을 때는 경고창을 설정하고 원래의 내용으로 돌아가는 기능 구현 필요합니다. 
우선은 콘솔창 및 화면 출력 기준으로 수정 변경 되는 것 확인했으나 실제 서버 배포 테스트 시에도 잘 작동하는지 확인할 필요가 있습니다.
> Feat: 댓글 등록 기능 중 파일 누락 부분 PR 

- client/package-lock.json
- client/package.json
* package.json에 @reduxjs/toolkit 라이브러리 추가되었습니다.
프로젝트 초기 구조화 작업할 때 분명 설치한 줄 알았는데 빠트렸네요;;
> Feat: Install/redux-toolkit을 설치한다.

- client/package-lock.json
- client/package.json
> Feat: react-redux를 설치한다.

- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* 포트폴리오 데이터 쿼리 캐싱 시간을 무한대로 수정하였습니다.
* 포트폴리오 내용 부분이 단어 단위로 줄바꿈 되도록 수정하였습니다.
* 수정된 MSW 데이터명을 반영했습니다.
> Fix: 포트폴리오 쿼리 캐싱 시간을 Infinity로 수정한다.

- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/search/Search.styled.tsx
- client/src/components/search/Search.tsx
- client/src/mocks/handlers.ts
- client/src/pages/community-add/AddCommunity.tsx
- client/src/pages/community-main/CommunityMain.tsx
import 리팩토링과 등록페이지 post 요청, search 엔터키 수정
- import 순서 리팩토링(라이브러리인 것 -> 아닌 것)
- 등록 페이지 msw 활용해 post 요청
- 함수로 onClick 에서 엔터키 작동 시키던 것 -> form으로 바꿔서 onSubmit 으로 변경
> Fix: import 리팩토링, post 기능 수정, search 기능 수정

- client/src/components/communityItem/CommunityItem.tsx
- client/src/mocks/handlers.ts
변수 명 수정(화면 렌더링 안되는 것 수정)
커뮤니티 아이템 컴포넌트 변수 명 수정
> fix: 커뮤니티 아이템 변수 명 수정

- client/src/utils/apiService.tsx
ApiService.tsx -> apiService.tsx 파일 명 수정
> fix: 파일 명 수정

- client/src/commons/atoms/header/CHeader.tsx
- client/src/commons/atoms/header/Header.tsx
- client/src/commons/molecules/Comment.tsx
- client/src/components/header/LogoHeader.tsx
- client/src/components/mypageIntroduce/MypageIntroduce.tsx
- client/src/mocks/handlers.ts
- client/src/modules/index.ts
- client/src/modules/loginSlice.ts
- client/src/pages/community-main/CommunityMain.tsx
- client/src/pages/mypage/Mypage.tsx
로그인 상태 전역 관리 1차 작성 PR 입니다. 
+ 금일 07.14 오전 fe-dev에서 pull 받은 후 몇 변수 이름 변경으로 인한 에러와 충돌 해결 한 파일도 함께 PR 합니다. 
-  loginSlice로 간단한 전체 로그인 상태 관리 코드 추가 
- handler 부분 변수 오타 수정
> Feat: 로그인 상태 전역 관리 1차 작성

- client/src/components/mypage-community/CommunityList.tsx
- client/src/components/pagenation/Pagenation.styled.tsx
- client/src/components/pagenation/Pagenation.tsx
- client/src/pages/mypage/Mypage.tsx
> [add] 마이페이지 기능 추가

- client/src/components/mypage-community/CommunityList.tsx
마이페이지의 게시판 부분에 태그가 없어져서 그 부분을 이름으로 수정하였습니다.
> [styled] 마이페이지 게시판 스타일 변경

- client/src/components/mypageIntroduce/MypageIntroduce.styled.tsx
- client/src/components/mypageProfile/MypageProfile.styled.tsx
마이페이지의 사용자 정보에 해당하는 컨테이너의 배경색상을 변경하였습니다.
> [styled] 마이페이지 마크업 수정

- client/src/components/graphicItem/GraphicItem.styled.tsx
- client/src/pages/main/Main.tsx
- client/src/types/reduxState.ts
메인페이지에서 '그래픽디자인'이미지가 보이지 않은 원인을 발견하고 수정하였습니다.
> [styled] 파일 수정

- client/src/components/deleteModal/DeleteModal.tsx
- client/src/components/mypageIntroduce/MypageIntroduce.tsx
마이페이지 회원탈퇴 confirm 대신 만들어진 모달 컴포넌트를 이용해 구현하였습니다.
> [styled] 회원탈퇴

- client/src/commons/atoms/buttons/revise-remove/ReviseBtn.tsx
- client/src/commons/atoms/header/CHeader.styled.tsx
- client/src/commons/molecules/Tag.tsx
- client/src/components/deleteModal/DeleteModal.tsx
- client/src/hooks/useModal.tsx
- client/src/mocks/data.ts
- client/src/mocks/handlers.ts
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
- client/src/types/index.ts
- client/src/types/portfolio.ts
* 포트폴리오 상세 페이지에서 수정 | 삭제 버튼을 추가했습니다.
* 작성자 본인일 경우에만 해당 버튼이 나타납니다.
* DeleteModal props에 deleteHandler 함수를 추가했습니다. 삭제 기능을 담고있는 함수를 전달하면 됩니다.
> Feat: 포트폴리오 삭제 기능을 구현한다.

- client/src/commons/atoms/logo/Logo.tsx
- client/src/components/editor/QuillEditor.tsx
- client/src/components/editor/TitleForm.tsx
- client/src/components/header/LogoHeader.tsx
- client/src/hooks/usePreventGoBack.tsx
- client/src/hooks/usePreventRefresh.tsx
- client/src/pages/portfolio-edit/PortfolioEdit.tsx
- client/src/types/quill.ts
* 포트폴리오 작성/수정 페이지에서 뒤로가기 혹은 새로고침 시 경고 모달이 오픈됩니다.
> Feat: 작성/수정 페이지에서 뒤로가기, 새로고침 시 경고창을 표시한다.

- client/src/components/editor/TitleForm.tsx
* 포트폴리오 작성/수정 페이지에 유효성 검증을 추가하였습니다.
* 본문, 제목, 태그, 요약문 조건 미충족 시 alert가 나타납니다.
> Feat: 포트폴리오 작성 페이지에 유효성 검증을 추가한다.

- client/index.html
- client/src/App.tsx
- client/src/commons/atoms/header/CHeader.tsx
- client/src/commons/styles/layout/Layout.styled.tsx
- client/src/components/headerDropdown/HeaderDropdown.tsx
- client/src/components/login/LoginGoogleForm.styled.tsx
- client/src/components/login/LoginGoogleForm.tsx
- client/src/components/modal/AlertModal.tsx
- client/src/mocks/data.ts
- client/src/mocks/handlers.ts
- client/src/modules/loginSlice.ts
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/login/Login.tsx
- client/src/pages/signup/SignUp.tsx
- client/src/utils/apiService.tsx
네틀리파이 배포 준비 - communityDetail 수정
- Modal 부분 함수 누락 부분 처리
- onConfirm과 onCancel 부분에 알맞은 함수를 넣어주시면 되구용 필요 없을 때는 DeleteButton이나 CancelButton을 안 넣어주시면 됩니당!
> Fix: 네틀리 파이 배포 준비 - communityDetail수정

- client/src/components/login/LoginGoogleForm.tsx
로그인 기능 1차 구현 중 누락 부분 업로드
- 구글 을 통해 로그인 진행 될 수 있도록 설정
- 클라이언트인지 파트너인지 선택 기능 구현 했으나 최초로그인인지 아닌지 구분필요
> Feat: 로그인 기능 구현 1차 

- client/src/App.tsx
- client/src/components/login/LoginGoogleForm.tsx
- client/src/mocks/handlers.ts
- client/src/pages/login/Login.tsx
- client/src/utils/apiService.tsx
- client/src/utils/cookie.tsx
로그인 구글 OAuth get/post 설정
- accesstoken 쿠키에서 받을 준비 구현
- 구글 버튼 클릭 시 로그인 기능 구현 (서버 테스트 미 완료)
> Feat: 구글 OAuth get/post 설정

- client/src/components/appItem/AppItem.tsx
- client/src/components/graphicItem/GraphicItem.styled.tsx
- client/src/components/graphicItem/GraphicItem.tsx
- client/src/components/photoItem/PhotoItem.styled.tsx
- client/src/components/photoItem/PhotoItem.tsx
- client/src/components/threeDitem/ThreeDITem.tsx
- client/src/components/threeDitem/ThreeDItem.styled.tsx
- client/src/components/webItem/WebItem.styled.tsx
- client/src/components/webItem/WebItem.tsx
- client/src/pages/main/Main.tsx
카테고리별 아이템 hover시, 제목, 작성자 이름이 보여지게 구현
> [Add] 메인페이지

- client/src/components/navbar/CategoryNavBar.tsx
- client/src/modules/categorySlice.ts
* CategoryNavBar 카테고리 타입 에러를 수정하였습니다.
> Fix: 카테고리 타입 에러를 수정한다.

- client/src/types/form.ts
> Fix: netlify 오류 원인을 제거한다.

- client/src/components/login/LoginGoogleForm.tsx
- client/src/pages/login/Login.tsx
- client/src/types/form.ts
> Fix: netlify 배포 준비 - 주석 처리

- client/package-lock.json
- client/src/components/detailContents/DetailContents.tsx
- client/src/pages/community-add/AddCommunity.tsx
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/community-main/CommunityMain.tsx
게시판 상세페이지 조회 , 수정, 삭제, 수정 기능 Proxy 이용해서 테스트 완료 및 수정 (임시 PR)
> Feat: 게시판 상세 페이지 조회, 수정, 삭제 수정 완료

- client/src/app-config.js
- client/src/app-config.ts
- client/src/utils/apiService.tsx
* `/src/app-config.ts` 파일에 배포 버전 서버 url 등록하시면 됩니다.
> Feat: 개발/배포 환경에 따라 다른 api_base_url을 등록한다.

- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* Tag as tag 별칭을 지우고 Tag 컴포넌트 이름을 PortfolioTag 로 수정하였습니다.
> Fix: Portfolio detail page Tag 컴포넌트 네이밍을 변경한다.

- client/src/App.tsx
- client/src/pages/community-add/AddCommunity.tsx
등록, 수정 페이지 코드 수정
- 등록 -> post 요청 코드 수정
- 수정 -> 코드 리팩토링
> fix: 등록, 수정 페이지 코드 수정

- client/src/components/search/Search.tsx
> fix: 검색창 이름 검색 주석처리

- client/src/App.tsx
- client/src/components/login/LoginGoogleForm.tsx
- client/src/components/login/SelectRole.styled.tsx
- client/src/components/login/SelectRole.tsx
- client/src/mocks/handlers.ts
- client/src/modules/loginSlice.ts
- client/src/pages/signup/SignUp.tsx
구글 OAuth 관련 1차 정리 
- 구글 accessToken 받아서 서버로 POST 준비 완료 
- isMember true | false 값으로 보내주는 것 확인 하고 역할 선택지 추가 예정
> Feat: 구글 OAuth 1차 정리

- client/src/components/home-section/animation-section/AnimationSection.styled.tsx
- client/src/components/home-section/app-section/AppSection.styled.tsx
- client/src/components/home-section/graphic-section/GraphicDesignSection.styled.tsx
- client/src/components/home-section/photography-section/PhotographySection.styled.tsx
- client/src/components/home-section/web-section/WebSection.styled.tsx
> [styled] 기선제압 수정

- client/src/components/navbar/CategoryNavBar.tsx
카테고리 버튼들의 div박스를 bg="transparent" 를 이용해 투명하게 처리하였습니다.
> [styled] 카테고리 div 박스

- client/src/pages/main/Main.styled.tsx
- client/src/pages/main/Main.tsx
메인페이지 데이터X 상태 이미지 
searchs에 값이 있으면 해당 데이터를 띄우고 없으면 이미지를 띄움
> Fix: 메인페이지 데이터 없을 때 띄우는 이미지 코드 수정

- client/src/pages/community-main/CommunityMain.styled.tsx
- client/src/pages/community-main/CommunityMain.tsx
게시판 메인 데이터 없을 때 이미지 페이지 수정
searchs에 데이터가 있으면 데이터 리스트 나열
없으면 nodata 이미지 출력
> Fix: 게시판 메인 데이터 없을 때 이미지 페이지

- client/src/components/titleForm/useTitleForm.ts
- client/src/hooks/useImageHandler.tsx
* 만약 게시판 작성 페이지 에디터에도 이미지 핸들러를 추가하고 싶을 경우를 대비해 이미지 삭제 함수를 useImageHandler 훅으로 옮겼습니다.
> Fix: 이미지 제거 함수를 useImageHandler 훅으로 옮긴다.

- client/src/components/search/Search.tsx
> fix: search props 타입 수정

- client/src/pages/main/Main.tsx
> Fix: RootState 코드 삭제

- client/src/pages/main/Main.tsx
> Fix: Main page add

- client/src/components/header/LogoHeader.tsx
- client/src/hooks/usePreventGoBack.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
- client/src/pages/portfolio-edit/PortfolioEdit.tsx
* 포트폴리오 작성 페이지에서 로고 이미지를 클릭했을 때 '정말 나가시겠습니까?' alert를 출력합니다.
* (원래 뒤로가기, 새로고침, 창닫기 시에만 출력했습니다)
> Fix: 포트폴리오 작성 페이지에서 로고 이미지를 클릭했을 때 경고가 뜬다.

- client/src/components/home-section/black-section/BlackSection.styled.tsx
- client/src/components/home-section/black-section/BlackSection.tsx
- client/src/pages/community-main/CommunityMain.styled.tsx
- client/src/pages/landingpage/LandingPage.tsx
nodata 이미지 위치 조정, 기선제압 블랙 섹션 추가
no data 이미지 position 조정
기선제압 페이지최상단에  페이지 전체 블랙인 페이지 추가
> fix: nodata 이미지 위치 조정, 기선제압 블랙 섹션 추가

- client/src/pages/login/Login.tsx
- client/src/pages/signup/SignUp.tsx
회원가입 link 경로 수정, 로그인 p태그 변경
회원가입 뒤로 가기 버튼 link 경로 /main 으로 수정
로그인 처음이신가요 부분 p 태그로 변경
> fix: 회원가입 link 경로 수정, 로그인 p태그 변경

- server/src/main/java/com/portfolly/server/bookmark/controller/BookmarkController.java
- server/src/main/java/com/portfolly/server/bookmark/service/BookmarkService.java
- server/src/main/java/com/portfolly/server/category/service/CategoryService.java
- server/src/main/java/com/portfolly/server/likes/controller/LikesController.java
- server/src/main/java/com/portfolly/server/likes/service/LikesService.java
- server/src/main/java/com/portfolly/server/member/dto/MemberDto.java
- server/src/main/java/com/portfolly/server/picture/controller/PictureController.java
- server/src/main/java/com/portfolly/server/picture/service/PictureService.java
- server/src/main/java/com/portfolly/server/portfolio/controller/PortfolioController.java
- server/src/main/java/com/portfolly/server/portfolio/dto/PortfolioDto.java
- server/src/main/java/com/portfolly/server/portfolio/mapper/PortfolioMapper.java
- server/src/main/java/com/portfolly/server/portfolio/service/PortfolioService.java
Reverts codestates-seb/seb44_main_013#272
> Revert "fix: portfolio delete, Picture, likes, bookmark"

- client/src/commons/atoms/buttons/category/CategoryButton.tsx
- client/src/commons/molecules/comment/Comment.tsx
- client/src/commons/molecules/comment/CommentWriteBox.tsx
- client/src/components/comment/CommentBox.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/detailContents/DetailContents.tsx
- client/src/components/home-section/black-section/BlackSection.tsx
- client/src/components/navbar/CategoryNavBar.tsx
- client/src/mocks/data.ts
- client/src/mocks/handlers.ts
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/community-main/CommunityMain.tsx
- client/src/pages/main/Main.tsx
- client/src/store/portfolioSlice.ts
- client/src/types/index.ts
네틀리파이 배포 에러 해결 작업 중 
- Category 한글 영어 인식 에러 
- UserProfile에서 memberId -> id , picture -> imageUrl 수정 작업
> Fix: 네틀리파이 배포 에러 해결 작업

- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/login/LoginGoogleForm.tsx
- client/src/components/modal/AlertModal.tsx
- client/src/mocks/handlers.ts
- client/src/pages/community-add/AddCommunity.tsx
- client/src/pages/community-detail/CommunityDetail.tsx
- client/src/pages/login/Login.tsx
- client/src/pages/main/Main.tsx
- client/src/pages/signup/SignUp.styled.tsx
- client/src/pages/signup/SignUp.tsx
- client/src/store/loginSlice.ts
- client/src/utils/apiService.tsx
- client/src/utils/axiosIntercept.tsx
전역으로 사용할 수 있는 axios 커스터마이징 버전 netaxios 구현 
네틀리 파이 배포 테스트 중
> Feat: 전역 axios (token포함) 기능 구현 및 네틀리파이 테스트

- client/netlify.toml
git push origin fe-feat/netlify-temp
> Fix: 네틀리파이 배포 응답 에러 해결 시도

- client/netlify.toml
- client/src/components/login/LoginGoogleForm.tsx
- client/src/main.tsx
- client/src/utils/apiService.tsx
- client/vite.config.ts
1. netlify.toml 기본으로 복귀 
* /api 설정
* /* 경로 route index.html 설정
2. LoginGoogleForm 기존 백업 자료와 비교해서 복귀
3. vite.config.ts에 hoomepage 복귀 
4. apiService 복귀
> Error: FE 배포 시도 1차 : 8080 복귀 및 netlify.toml 복귀

- client/index.html
- client/src/utils/apiService.tsx
- client/vite.config.ts
1. index.html 에 `    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />` 추가
2. vite.config.js에서 base 네틀리파이 주소 삭제
* 응답이 index.html로 오는게 얘 때문일 수도 
3. api 기본 http 로 수정
> Err: index.html meta 추가, api http로 수정 및 base 설정 삭제

- client/netlify.toml
- client/src/utils/apiService.tsx
1. netlify.toml 에서 route 설정 제거
> Err: netlify.toml route 설정 삭제

- client/src/pages/main/Main.tsx
> Fix: 데이터 없음 알림 창 생성

- client/netlify.toml
- client/src/utils/apiService.tsx
배포 주소 ec2 -> portfolly.site 로 시도
> Error:  배포 주소 변경 시도 

- client/src/components/appItem/AppItem.tsx
- client/src/components/graphicItem/GraphicItem.tsx
- client/src/components/login/LoginGoogleForm.tsx
- client/src/components/photoItem/PhotoItem.tsx
- client/src/components/threeDitem/ThreeDITem.tsx
- client/src/pages/login/Login.tsx
- api 주소 / 미스로 수정 현재 : portfolly.site
- 로그인 기능 임시 보류
- 메인 카테고리 API 에 맞게 수정
> Feat: 메인 아이켐 api 맞춰서 수정 및 로그인 기능 링크 주석

- client/src/components/mypageIntroduce/MypageIntroduce.tsx
- client/src/components/mypageProfile/MypageProfile.tsx
마이페이지의 유저 프로필 수정 시 PUT. -> PATCH 로 변경 합니다.
> Fix: mypage의 회원 수정 부분 PATCH 로 변경

- client/src/components/appItem/AppItem.tsx
- client/src/components/graphicItem/GraphicItem.tsx
- client/src/components/login/LoginGoogleForm.tsx
- client/src/components/photoItem/PhotoItem.tsx
- client/src/components/threeDitem/ThreeDITem.tsx
- client/src/components/webItem/WebItem.tsx
- client/src/pages/main/Main.tsx
- client/src/utils/apiService.tsx
- 메인 페이지 WEB 아이템 null 경우 대체 이미지 적용 
나머지는 이미지 없이 넣을 예정. 
- apiService 개발/배포 전부  배포 주소로 요청
> Fix: 메인 페이지 이미지 null 경우 대체 이미지 적용

- client/src/App.tsx
- client/src/pages/community-edit/EditCommunity.styled.tsx
- client/src/pages/community-edit/EditCommunity.tsx
게시판 등록 수정 코드 분리
AddCommunity 와 EditCommunity 로 페이지 분리
> fix: 등록 수정 코드 분리

- client/src/components/login/LoginGoogleForm.tsx
- client/src/components/login/SelectRole.tsx
- client/src/utils/apiService.tsx
> Fix: 포트폴리오 상세 페이지 call 함수 수정

- client/src/components/communityItem/CommunityItem.tsx
- client/src/types/index.ts
> Fix: userProfile amend

- client/src/components/communityItem/CommunityItem.styled.tsx
- client/src/components/communityItem/CommunityItem.tsx
- client/src/components/search/Search.tsx
- client/src/pages/community-add/AddCommunity.tsx
- client/src/pages/community-edit/EditCommunity.tsx
- client/src/pages/community-main/CommunityMain.styled.tsx
- client/src/pages/community-main/CommunityMain.tsx
검색, ui 수정, 리액트 퀼 엔터 시 br 태그 제거
> Fix: community function

- client/src/utils/axiosIntercept.tsx
> fix: axios Bearer delete

- client/src/commons/atoms/buttons/Button.styled.tsx
- client/src/components/detailContents/DetailContents.styled.tsx
- client/src/components/detailContents/DetailContents.tsx
- client/src/pages/community-main/CommunityMain.tsx
게시판 목록으로 돌아오는 버튼 구현
writing 버튼 로그인 유무에 따른 렌더링
> Fe feat/community function

- client/src/components/headerDropdown/HeaderDropdown.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.tsx
* Header 프로필 이미지 클릭 시 파트너 회원만 dropdown 메뉴에 'new portfolio' 가 나타나게 수정합니다.
> Feat: 파트너 회원만 포트폴리오 작성 버튼이 보이게 한다.

- client/src/components/headerDropdown/HeaderDropdown.tsx
> Fix: 마이페이지로 드롭다운 링크 연결

- client/src/pages/community-detail/CommunityDetail.tsx
> Fix: 댓글 리렌더 트리거 수정

- client/src/components/mypage-community/CommunityList.tsx
- client/src/components/mypageItem/MypageItem.tsx
- client/src/pages/mypage/Mypage.tsx
- client/src/types/index.ts
- 마이페이지에서 내가 쓴 게시글 클릭 시 해당 게시물로 이동 링크 연결 
- 마이페이지 북마크 데이터가 id 값만 불러와집니다.
> Fix: 마이페이지에서 게시판 링크 연결

- client/src/pages/community-main/CommunityMain.tsx
무한스크롤 1차 구현
무한스크롤 구현
디비전 별 내용 잘 불러오는지 확인
협업 카테고리로 넘어올 때 생기는 데이터 출처확인
로딩 이미지 삽입
> Feat: 무한스크롤 1차 구현

- client/src/components/login/LoginGoogleForm.tsx
- client/src/pages/login/Login.styled.tsx
- client/src/pages/login/Login.tsx
로그인 사이트 UI 디자인 1차 쉊ㅇ
로그인 파트 자체 로그인 폼 생성 
기존
변경
> Design: 로그인 사이트 UI 디자인 1차 수정

- client/src/commons/molecules/comment/CommentWriteBox.tsx
- client/src/store/memberSlice.ts
memberSlice 에서 유저 정보 (이미지, 이름) localStorage 에서 저장 후 관리 위한 작업
> Fix: memberSlice 에서 유저 정보 localstorage에서 입수 위한 준비

- client/src/commons/molecules/profile/MemberProfile.tsx
* MemberProfile.tsx 컴포넌트 코드를 KISS 원칙에 따라 수정하였습니다.
> Fix: 멤버 프로필 컴포넌트를 KISS원칙으로 변경한다.

- client/package-lock.json
- client/package.json
- client/src/GlobalStyles.tsx
- client/src/commons/molecules/profile/MemberProfile.styled.tsx
- client/src/commons/molecules/profile/MemberProfile.tsx
- client/src/main.tsx
- client/src/twinTypes/twin.d.ts
- client/tsconfig.json
- client/vite.config.ts
- package-lock.json
* twin.mcro 라이브러리에서 styled를 불러올 수 있게 수정했습니다.
> Fe fix/styled refactoring

- client/src/commons/molecules/comment/Comment.styled.tsx
- client/src/commons/molecules/dropdown/CategoryDropdown.styled.tsx
- client/src/commons/molecules/tag/Tag.styled.tsx
- client/src/commons/styles/Containers.styled.tsx
- client/src/commons/styles/layout/Layout.styled.tsx
- client/src/components/dropdown/Dropdown.styled.tsx
- client/src/components/header/Header.styled.tsx
- client/src/components/header/LogoHeader.tsx
- client/src/components/headerDropdown/HeaderDropdown.styled.tsx
- client/src/components/titleForm/TitleForm.styled.tsx
- client/src/pages/portfolio-detail/PortfolioDetail.styled.tsx
- client/src/pages/portfolio-edit/PortfolioEdit.styled.tsx
* 제가 구현한 컴포넌트에 한해 모든 styled를 twin.macro에서 가져오는 걸로 수정했습니다.
> Fix: twin.macro에서 styled를 가져온다.
